//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_admin
    {
        public int id { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string nickname { get; set; }
        public Nullable<int> power { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
