//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_room_info
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string link_name { get; set; }
        public Nullable<int> stop_car_area { get; set; }
        public Nullable<System.DateTime> construct_date { get; set; }
        public Nullable<int> road_area { get; set; }
        public Nullable<int> room_area { get; set; }
        public Nullable<int> lh_area { get; set; }
        public Nullable<int> room_number { get; set; }
        public string address { get; set; }
        public string remark { get; set; }
    }
}
